# Generated by Django 5.2.4 on 2025-07-31 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='nome',
            new_name='nome_item',
        ),
    ]
