# Generated by Django 5.2.4 on 2025-07-27 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='endereco_supermercado',
            field=models.TextField(default='Endereço não informado', verbose_name='Endereço do estabelecimento'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='fim_promocao',
            field=models.DateField(blank=True, null=True, verbose_name='Data do fim da promoção'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='inicio_promocao',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de início'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='numero_telefone',
            field=models.CharField(default='Não informado', max_length=15, verbose_name='Telefone do estabelecimento'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='titulo_promocao',
            field=models.CharField(default='Oferta especial', max_length=100, verbose_name='Título da Promoção'),
        ),
    ]
