# Generated by Django 5.2.4 on 2025-07-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_oferta_endereco_supermercado_oferta_fim_promocao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='fim_promocao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
