# Generated by Django 5.2.4 on 2025-08-05 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0003_alter_oferta_fim_promocao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supermercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_supermercado', models.CharField(max_length=100, verbose_name='Nome do supermercado')),
                ('endereco_supermercado', models.TextField(default='Endereço não informado', verbose_name='Endereço do estabelecimento')),
                ('numero_telefone', models.CharField(default='Não informado', max_length=15, verbose_name='Telefone do estabelecimento')),
            ],
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='endereco_supermercado',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='nome_supermercado',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='numero_telefone',
        ),
        migrations.AddField(
            model_name='oferta',
            name='supermercado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='oferta_supermercado', to='ofertas.supermercado'),
            preserve_default=False,
        ),
    ]
